### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by w96k** [castwide/backport#2]
Hello,
I have created package definition for guix (http://guix.info) with your package. Ruby Gems doesn't have "spec" folder, so I need to checkout from git in order to run tests. The problem is that without tags I can't checkout specific version, so right now it is a hard-coded commit string. It would be nice to have release tags from now on to update your package in guix in future.

**Comment by castwide** [comment]
No problem. I added a tag for the most recent release (v1.1.1) and will push tags for future releases as well.

**Comment by w96k** [comment]
Thanks (:
